{% set version = "3.1.0" %}

package:
  name: xmsinterp
  version: {{ version }}

source:
  url: https://github.com/Aquaveo/xmsinterp/archive/{{ version }}.tar.gz
  sha256: e8705b6b44e2cd121fed93417072bf5d4ae51615a61148cc0f824d242f6df603

build:
  number: 1
  skip: True  # [py27]
  merge_build_host: true

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.0.0
    # just to avoid build/host merge issues
    # but these should be in host.
    - zlib
    - xmscore
    - xmsgrid
    - python
    - pybind11=2.2
    - boost-cpp
    - pip
  run:
    - xmscore
    - xmsgrid
    - python
    - numpy

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - xms.interp

about:
  home: aquaveo.com
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "Interpolation library for XMS libraries and products"
  doc_url: https://aquaveo.github.io/xmsinterp
  dev_url: https://github.com/Aquaveo/xmsinterp

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
