{% set version = "3.1.1" %}

package:
  name: xmsinterp
  version: {{ version }}

source:
  url: https://github.com/Aquaveo/xmsinterp/archive/{{ version }}.tar.gz
  sha256: b8666a0cb6b93ef804acd308372aa4dbfd592b3d3f0a0695604114e2ab994f49
  patches:
    - 0001-Fix-pybind11-cmake-path.patch

build:
  number: 0
  skip: True  # [py27]
  merge_build_host: true

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.0.0
    # just to avoid build/host merge issues
    # but these should be in host.
    - zlib
    - xmscore
    - xmsgrid
    - python
    # need newer pybind11 builds for cmake path patch
    - pybind11 >2.3.0
    - boost-cpp
    - pip
  run:
    - xmscore
    - xmsgrid
    - python
    - numpy

test:
  source_files:
    - _package/*.py
    - _package/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./_package/tests
  imports:
    - xms.interp

about:
  home: aquaveo.com
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "Interpolation library for XMS libraries and products"
  doc_url: https://aquaveo.github.io/xmsinterp
  dev_url: https://github.com/Aquaveo/xmsinterp

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
