{% set version = "3.1.2" %}

package:
  name: xmsinterp
  version: {{ version }}

source:
  url: https://github.com/Aquaveo/xmsinterp/archive/{{ version }}.tar.gz
  sha256: 4466548af242750e16eea6b60b3d773594bef3f2ea28d311d9d4bcc0a05f3a37

build:
  number: 0
  skip: true  # [py27]
  merge_build_host: true

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.0.0
    # just to avoid build/host merge issues
    # but these should be in host.
    - zlib
    - xmscore
    - xmsgrid
    - python
    - pybind11=2.2
    - boost-cpp
    - pip
  run:
    - xmscore
    - xmsgrid
    - python
    - numpy

test:
  source_files:
    - _package/*.py
    - _package/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./_package/tests
  imports:
    - xms.interp

about:
  home: aquaveo.com
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Interpolation library for XMS libraries and products
  doc_url: https://aquaveo.github.io/xmsinterp
  dev_url: https://github.com/Aquaveo/xmsinterp

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
