travis:
  secure:
    BINSTAR_TOKEN: W/s2eyYD7rpDK7hrUPd863VFVQyapUNqp8bkBAQwpC/cjrqzvydNb962JmfEARPLnQJt8kjGQeoE3F7+GfmE7nFT0QIsuffoDNrqwdB1762GG20XCB/Y2MvbXiMaKGJCAc2bV3T+VbkKJfC3c5HuWcCnbiVK1YgSEoXqLkFw5VRKnV5Wdr8H7mpjJlZxIf/++lNsiutslG4aI5P2aJQ2uyBBFIDs0qFl76SWJ/K8Wu8puUFZo2e616Qd0ubqljZwlnp9s2PLOvvhU/dyhKAD2tksasbvZwkS1mHBF9kI81anFKt9W+dUvE8xwYVZ5S75TsHBTDdfTD+07vHIH/zA8CpLOkba7M0+TjZbADn0DpeNrwMDkSN5trXk/1PPd7J7Tja3QFHD0pws2M+ksqMvZyMhs7gnjSvcjElb4WKkmLoJ6r+Ayhg27jV23HssgytnIBK9CjH5buXrxsCfRkiGPAZjM57p4pS4ulYAmWdo4DM9S3mRDRCQnz5pnN0GudbI+imu/zUuiwv+wcgAWlvgmBdDrMWnRn5z2TRhAfcSbKS3xqSsWeWSbGOrmeyyH0FF83bbA+7J7p8+XX/1UY+tembaQX5/9A+q1fD3oMILnebg4blfP3D1+sw1s/YStgNDGS4ie+LN2ps/VgMpfwf1ALaOmBIKQf8u2pp3jdMVmAk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
